spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/quizdb
spring.datasource.username=postgres
spring.datasource.password=parola123

spring.jpa.hibernate.ddl-auto=update